import type { DashboardData } from '../types/index.js';

export function generateReport(data: DashboardData, format: 'md' | 'txt'): string {
  if (format === 'md') {
    return generateMarkdownReport(data);
  }
  return generateTextReport(data);
}

function generateMarkdownReport(data: DashboardData): string {
  const lines: string[] = [];
  const date = new Date(data.timestamp).toLocaleDateString('en-US', {
    weekday: 'long',
    year: 'numeric',
    month: 'long',
    day: 'numeric',
  });

  lines.push(`# 📊 MonForge Health Report`);
  lines.push(`> Generated: ${date}`);
  lines.push('');

  // Stats
  if (data.stats.length > 0) {
    lines.push('## 📈 Application Health');
    lines.push('');
    lines.push('| Provider | Crash-Free Rate | Crash-Free Users | Total Crashes | ANR Rate |');
    lines.push('|----------|----------------|-----------------|--------------|----------|');
    for (const s of data.stats) {
      lines.push(
        `| ${s.provider} | ${s.data.crashFreeRate.toFixed(2)}% | ${s.data.crashFreeUsersRate.toFixed(2)}% | ${s.data.totalCrashes} | ${s.data.anrRate.toFixed(2)}% |`
      );
    }
    lines.push('');
  }

  // Ratings
  if (data.ratings.length > 0) {
    lines.push('## ⭐ App Store Ratings');
    lines.push('');
    for (const r of data.ratings) {
      lines.push(`### ${r.provider}`);
      lines.push(`- **Average**: ${r.data.average.toFixed(1)} / 5.0`);
      lines.push(`- **Total Reviews**: ${r.data.total.toLocaleString()}`);
      lines.push(`- **Distribution**: ⭐5: ${r.data.distribution[5]} | ⭐4: ${r.data.distribution[4]} | ⭐3: ${r.data.distribution[3]} | ⭐2: ${r.data.distribution[2]} | ⭐1: ${r.data.distribution[1]}`);
      lines.push('');
    }
  }

  // Top Errors
  if (data.errors.length > 0) {
    lines.push('## 🐛 Top Errors');
    lines.push('');
    for (const e of data.errors) {
      lines.push(`### ${e.provider}`);
      lines.push('');
      lines.push('| # | Error | Count | Users | Level |');
      lines.push('|---|-------|-------|-------|-------|');
      e.data.slice(0, 10).forEach((err, i) => {
        lines.push(`| ${i + 1} | ${err.title} | ${err.count} | ${err.userCount} | ${err.level} |`);
      });
      lines.push('');
    }
  }

  // Alerts
  if (data.alerts.length > 0) {
    lines.push('## 🚨 Alert Violations');
    lines.push('');
    for (const v of data.alerts) {
      const icon = v.severity === 'critical' ? '🔴' : v.severity === 'warning' ? '🟡' : 'ℹ️';
      lines.push(`- ${icon} **${v.rule.name}**: ${v.message}`);
    }
    lines.push('');
  }

  lines.push('---');
  lines.push('*Generated by [MonForge](https://github.com/magicpro97/monforge)*');

  return lines.join('\n');
}

function generateTextReport(data: DashboardData): string {
  const lines: string[] = [];
  const date = new Date(data.timestamp).toLocaleDateString();

  lines.push('═══════════════════════════════════════════');
  lines.push('  📊 MonForge Health Report');
  lines.push(`  Generated: ${date}`);
  lines.push('═══════════════════════════════════════════');
  lines.push('');

  if (data.stats.length > 0) {
    lines.push('── Application Health ──');
    for (const s of data.stats) {
      lines.push(`  ${s.provider}:`);
      lines.push(`    Crash-Free Rate:  ${s.data.crashFreeRate.toFixed(2)}%`);
      lines.push(`    Crash-Free Users: ${s.data.crashFreeUsersRate.toFixed(2)}%`);
      lines.push(`    Total Crashes:    ${s.data.totalCrashes}`);
      lines.push(`    ANR Rate:         ${s.data.anrRate.toFixed(2)}%`);
      lines.push('');
    }
  }

  if (data.ratings.length > 0) {
    lines.push('── App Store Ratings ──');
    for (const r of data.ratings) {
      lines.push(`  ${r.provider}: ${r.data.average.toFixed(1)}/5.0 (${r.data.total} reviews)`);
    }
    lines.push('');
  }

  if (data.errors.length > 0) {
    lines.push('── Top Errors ──');
    for (const e of data.errors) {
      lines.push(`  ${e.provider}:`);
      e.data.slice(0, 10).forEach((err, i) => {
        lines.push(`    ${i + 1}. ${err.title} (${err.count}x, ${err.userCount} users)`);
      });
      lines.push('');
    }
  }

  if (data.alerts.length > 0) {
    lines.push('── Alert Violations ──');
    for (const v of data.alerts) {
      const icon = v.severity === 'critical' ? '[CRITICAL]' : v.severity === 'warning' ? '[WARNING]' : '[INFO]';
      lines.push(`  ${icon} ${v.rule.name}: ${v.message}`);
    }
    lines.push('');
  }

  lines.push('───────────────────────────────────────────');
  lines.push('  Generated by MonForge');

  return lines.join('\n');
}
